# Generated by Django 2.2.4 on 2020-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yas_store', '0002_auto_20201023_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
